### ISSUE TITLE
Would it be possible to share the script to calculate bias score?

### ISSUE THREAD

**Issue by mdkma** [nyu-mll/BBQ#2]
Hi! I'm wondering would it be possible to share the script to calculate the bias score for both disambiguated contexts and ambiguous contexts described in Section 5 of the paper? It would be super nice and much appreciated to make sure we are following the exact way to calculate the score as designed. Thanks a lot!

**Comment by Alicia-Parrish** [comment]
Uploaded an R script that gives an example of calculating bias score using `target_loc` from the metadata file (`analysis_scripts/BBQ_calculate_bias_score.R`), with the updated file values. Note that there's still a minor issue in the `gender_identity` category where I haven't been able to recreate the exact numbers of the paper that I'm still looking into, but the trends are all the same and the other categories match, so I'm pushing this script and looking into the discrepancy still.

**Comment by mdkma** [comment]
Thanks a lot Alicia! I'll look into the script.
